steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/foreclosurefinderapp'
      - '.'
    # secretEnv:
    #   - 'GOOGLE_CLOUD_RUN_ENABLE_HTTP2'
    #   - 'SERVICE_ACCOUNT_KEY'
    #   - 'TYPE'
    #   - 'PROJECT_ID'
    #   - 'PRIVATE_KEY_ID'
    #   - 'PRIVATE_KEY'
    #   - 'CLIENT_EMAIL'
    #   - 'CLIENT_ID'
    #   - 'AUTH_URI'
    #   - 'TOKEN_URI'
    #   - 'AUTH_PROVIDER_X509_CERT_URL'
    #   - 'CLIENT_X509_CERT_URL'
    #   - 'UNIVERSE_DOMAIN'
      
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/foreclosurefinderapp']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'foreclosure-finder-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/foreclosurefinderapp'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--set-env-vars=GOOGLE_CLOUD_RUN_ENABLE_HTTP2=true'
      - '--set-env-vars=SERVICE_ACCOUNT_KEY={$_SERVICE_ACCOUNT_KEY}'
      - '--set-env-vars=TYPE={$_TYPE}'
      - '--set-env-vars=PROJECT_ID={$_PROJECT_ID}'
      - '--set-env-vars=PRIVATE_KEY_ID={$_PRIVATE_KEY_ID}'
      - '--set-env-vars=PRIVATE_KEY={$_PRIVATE_KEY}'
      - '--set-env-vars=CLIENT_EMAIL={$_CLIENT_EMAIL}'
      - '--set-env-vars=CLIENT_ID={$_CLIENT_ID}'
      - '--set-env-vars=AUTH_URI={$_AUTH_URI}'
      - '--set-env-vars=TOKEN_URI={$_TOKEN_URI}'
      - '--set-env-vars=AUTH_PROVIDER_X509_CERT_URL={$_AUTH_PROVIDER_X509_CERT_URL}'
      - '--set-env-vars=CLIENT_X509_CERT_URL={$_CLIENT_X509_CERT_URL}'
      - '--set-env-vars=UNIVERSE_DOMAIN={$_UNIVERSE_DOMAIN}'
  
  # # Update Cloud Run service to enable HTTP/2 connections
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'services'
  #     - 'update'
  #     - 'foreclosure-finder-backend'
  #     - '--region'
  #     - 'us-central1'
  #     - '--ingress'
  #     - 'all'
  #     - '--platform'
  #     - 'managed'
  #     - '--set-env-vars'
  #     - 'GOOGLE_CLOUD_RUN_ENABLE_HTTP2=true'
  #     - 'SERVICE_ACCOUNT_KEY={$_SERVICE_ACCOUNT_KEY}'
  #     - 'TYPE={$_TYPE}'
  #     - 'PROJECT_ID={$_PROJECT_ID}'
  #     - 'PRIVATE_KEY_ID={$_PRIVATE_KEY_ID}'
  #     - 'PRIVATE_KEY={$_PRIVATE_KEY}'
  #     - 'CLIENT_EMAIL={$_CLIENT_EMAIL}'
  #     - 'CLIENT_ID={$_CLIENT_ID}'
  #     - 'AUTH_URI={$_AUTH_URI}'
  #     - 'TOKEN_URI={$_TOKEN_URI}'
  #     - 'AUTH_PROVIDER_X509_CERT_URL={$_AUTH_PROVIDER_X509_CERT_URL}'
  #     - 'CLIENT_X509_CERT_URL={$_CLIENT_X509_CERT_URL}'
  #     - 'UNIVERSE_DOMAIN={$_UNIVERSE_DOMAIN}'

  # # Update Cloud Run service to send all traffic to the latest revision
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'services'
  #     - 'update-traffic'
  #     - 'foreclosure-finder-backend'
  #     - '--to-latest'
  #     - '--platform=managed'
  #     - '--region'
  #     - 'us-central1'
  #     - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY