steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    # entrypoint: 'bash'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/foreclosurefinderapp'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/foreclosurefinderapp']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'foreclosure-finder-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/foreclosurefinderapp'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

  # # Update Cloud Run service to send all traffic to the latest revision
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'services'
  #     - 'update-traffic'
  #     - 'foreclosure-finder-backend'
  #     - '--to-latest'
  #     - '--platform=managed'
  #     - '--region'
  #     - 'us-central1'
  #     - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY