steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    # entrypoint: 'bash'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/foreclosurefinderapp'
      - '.'
    secretEnv: [
      'SERVICE_ACCOUNT_KEY',
      'TYPE', 
      'PROJECT_ID',
      'PRIVATE_KEY_ID',
      'PRIVATE_KEY',
      'CLIENT_EMAIL',
      'CLIENT_ID',
      'AUTH_URI',
      'TOKEN_URI',
      'AUTH_PROVIDER_X509_CERT_URL',
      'CLIENT_X509_CERT_URL',
      'UNIVERSE_DOMAIN'
    ]
      
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/foreclosurefinderapp']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'foreclosure-finder-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/foreclosurefinderapp'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_RUN_ENABLE_HTTP2=true'
      - 'SERVICE_ACCOUNT_KEY=$$_SERVICE_ACCOUNT_KEY'
      - 'TYPE=$$_TYPE'
      - 'PROJECT_ID=$$_PROJECT_ID'
      - 'PRIVATE_KEY_ID=$$_PRIVATE_KEY_ID'
      - 'PRIVATE_KEY=$$_PRIVATE_KEY'
      - 'CLIENT_EMAIL=$$_CLIENT_EMAIL'
      - 'CLIENT_ID=$$_CLIENT_ID'
      - 'AUTH_URI=$$_AUTH_URI'
      - 'TOKEN_URI=$$_TOKEN_URI'
      - 'AUTH_PROVIDER_X509_CERT_URL=$$_AUTH_PROVIDER_X509_CERT_URL'
      - 'CLIENT_X509_CERT_URL=$$_CLIENT_X509_CERT_URL'
      - 'UNIVERSE_DOMAIN=$$_UNIVERSE_DOMAIN'
  
  # Secret Manager Configuration
  # availableSecrets:
  #   secretManager:
  #     - versionName: projects/$PROJECT_ID/secrets/SERVICE_ACCOUNT_KEY/versions/latest
  #       env: 'SERVICE_ACCOUNT_KEY'
  #     - versionName: projects/$PROJECT_ID/secrets/TYPE/versions/latest
  #       env: 'TYPE'
  #     - versionName: projects/$PROJECT_ID/secrets/PROJECT_ID/versions/latest
  #       env: 'PROJECT_ID'
  #     - versionName: projects/$PROJECT_ID/secrets/PRIVATE_KEY_ID/versions/latest
  #       env: 'PRIVATE_KEY_ID'
  #     - versionName: projects/$PROJECT_ID/secrets/PRIVATE_KEY/versions/latest
  #       env: 'PRIVATE_KEY'
  #     - versionName: projects/$PROJECT_ID/secrets/CLIENT_EMAIL/versions/latest
  #       env: 'CLIENT_EMAIL'
  #     - versionName: projects/$PROJECT_ID/secrets/CLIENT_ID/versions/latest
  #       env: 'CLIENT_ID'
  #     - versionName: projects/$PROJECT_ID/secrets/AUTH_URI/versions/latest
  #       env: 'AUTH_URI'
  #     - versionName: projects/$PROJECT_ID/secrets/TOKEN_URI/versions/latest
  #       env: 'TOKEN_URI'
  #     - versionName: projects/$PROJECT_ID/secrets/AUTH_PROVIDER_X509_CERT_URL/versions/latest
  #       env: 'AUTH_PROVIDER_X509_CERT_URL'
  #     - versionName: projects/$PROJECT_ID/secrets/CLIENT_X509_CERT_URL/versions/latest
  #       env: 'CLIENT_X509_CERT_URL'
  #     - versionName: projects/$PROJECT_ID/secrets/UNIVERSE_DOMAIN/versions/latest
  #       env: 'UNIVERSE_DOMAIN'
  
  # # Update Cloud Run service to enable HTTP/2 connections
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'services'
  #     - 'update'
  #     - 'foreclosure-finder-backend'
  #     - '--region'
  #     - 'us-central1'
  #     - '--ingress'
  #     - 'all'
  #     - '--platform'
  #     - 'managed'
  #     - '--set-env-vars'
  #     - 'GOOGLE_CLOUD_RUN_ENABLE_HTTP2=true'
  #     - 'SERVICE_ACCOUNT_KEY={$_SERVICE_ACCOUNT_KEY}'
  #     - 'TYPE={$_TYPE}'
  #     - 'PROJECT_ID={$_PROJECT_ID}'
  #     - 'PRIVATE_KEY_ID={$_PRIVATE_KEY_ID}'
  #     - 'PRIVATE_KEY={$_PRIVATE_KEY}'
  #     - 'CLIENT_EMAIL={$_CLIENT_EMAIL}'
  #     - 'CLIENT_ID={$_CLIENT_ID}'
  #     - 'AUTH_URI={$_AUTH_URI}'
  #     - 'TOKEN_URI={$_TOKEN_URI}'
  #     - 'AUTH_PROVIDER_X509_CERT_URL={$_AUTH_PROVIDER_X509_CERT_URL}'
  #     - 'CLIENT_X509_CERT_URL={$_CLIENT_X509_CERT_URL}'
  #     - 'UNIVERSE_DOMAIN={$_UNIVERSE_DOMAIN}'

  # # Update Cloud Run service to send all traffic to the latest revision
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'services'
  #     - 'update-traffic'
  #     - 'foreclosure-finder-backend'
  #     - '--to-latest'
  #     - '--platform=managed'
  #     - '--region'
  #     - 'us-central1'
  #     - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY