steps:
  # Fetch the secrets from Secrets Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch secret values
        export SECRETS=$(gcloud secrets versions access latest --secret="all_secrets")
        # Parse secret values
        export SERVICE_ACCOUNT_KEY=$(echo "$SECRETS" | jq -r '.SERVICE_ACCOUNT_KEY')
        export TYPE=$(echo "$SECRETS" | jq -r '.TYPE')
        export PROJECT_ID=$(echo "$SECRETS" | jq -r '.PROJECT_ID')
        export PRIVATE_KEY_ID=$(echo "$SECRETS" | jq -r '.PRIVATE_KEY_ID')
        export PRIVATE_KEY=$(echo "$SECRETS" | jq -r '.PRIVATE_KEY')
        export CLIENT_EMAIL=$(echo "$SECRETS" | jq -r '.CLIENT_EMAIL')
        export CLIENT_ID=$(echo "$SECRETS" | jq -r '.CLIENT_ID')
        export AUTH_URI=$(echo "$SECRETS" | jq -r '.AUTH_URI')
        export TOKEN_URI=$(echo "$SECRETS" | jq -r '.TOKEN_URI')
        export AUTH_PROVIDER_X509_CERT_URL=$(echo "$SECRETS" | jq -r '.AUTH_PROVIDER_X509_CERT_URL')
        export CLIENT_X509_CERT_URL=$(echo "$SECRETS" | jq -r '.CLIENT_X509_CERT_URL')
        export UNIVERSE_DOMAIN=$(echo "$SECRETS" | jq -r '.UNIVERSE_DOMAIN')

  # Build and deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/foreclosurefinderapp'
      - '.'
      - '&'
      - 'gcr.io/cloud-builders/gcloud'
      - 'run'
      - 'deploy'
      - 'foreclosure-finder-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/foreclosurefinderapp'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_RUN_ENABLE_HTTP2=true'
      - '--set-secrets'
      - 'SERVICE_ACCOUNT_KEY=$SERVICE_ACCOUNT_KEY'
      - 'TYPE=$TYPE'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'PRIVATE_KEY_ID=$PRIVATE_KEY_ID'
      - 'PRIVATE_KEY=$PRIVATE_KEY'
      - 'CLIENT_EMAIL=$CLIENT_EMAIL'
      - 'CLIENT_ID=$CLIENT_ID'
      - 'AUTH_URI=$AUTH_URI'
      - 'TOKEN_URI=$TOKEN_URI'
      - 'AUTH_PROVIDER_X509_CERT_URL=$AUTH_PROVIDER_X509_CERT_URL'
      - 'CLIENT_X509_CERT_URL=$CLIENT_X509_CERT_URL'
      - 'UNIVERSE_DOMAIN=$UNIVERSE_DOMAIN'

  # Update Cloud Run service to send all traffic to the latest revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'foreclosure-finder-backend'
      - '--to-latest'
      - '--platform=managed'
      - '--region'
      - 'us-central1'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY